### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by knowneuropean** [jordanjoz1/flickr-views-counter#1]
Today, when I run my usual flickr stats counter, I receive the following error message:

Traceback (most recent call last):
  File "count-views.2.py", line 97, in <module>
    main(args.user_id, args.output)
  File "count-views.2.py", line 36, in main
    data.append(get_photo_data(photo.get('id')))
  File "count-views.2.py", line 74, in get_photo_data
    info = flickr.photos.getinfo(photo_id=photo_id)
  File "/usr/local/lib/python2.7/dist-packages/flickrapi/call_builder.py", line 37, in **call**
    return self.flickrapi_object.do_flickr_call(self.method_name, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flickrapi/core.py", line 319, in do_flickr_call
    *_params)
  File "/usr/local/lib/python2.7/dist-packages/flickrapi/core.py", line 381, in _wrap_in_parser
    data = wrapped_method(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flickrapi/core.py", line 359, in _flickr_call
    reply = self.flickr_oauth.do_request(self.REST_URL, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flickrapi/auth.py", line 255, in do_request
    raise exceptions.FlickrError('do_request: Status code %s received' % req.status_code)
flickrapi.exceptions.FlickrError: do_request: Status code 502 received

**Comment by knowneuropean** [comment]
Looks like it was a temporary flickr issue, sorry for the mistaken report, and thank you for this wonderful program!

**Comment by jordanjoz1** [comment]
Thanks anyway for the report. And I'm glad it's useful!
